[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    me-no-dev/ESPAsyncWebServer@^1.2.3
    bblanchon/ArduinoJson@^7.0.0
board_build.filesystem = littlefs
